Repository sebastianks/volcano, pull requests merged in 2021-01, with the labels that each got.

#15 Renames setup.php to index.php when setting up
  config/index.php
Labels: bug

#18 Add PHP composer action
  .github/workflows/php.yml
  composer.json
Labels: enhancement

#24 Renamed config directory
  README.md
  setup/.htaccess
  setup/index.php
  setup/site/pages/404.md
  setup/site/pages/default.md
  setup/site/pages/hello-world.md
  setup/site/theme/footer.php
  setup/site/theme/header.php
  setup/site/theme/index.php
  setup/site/theme/src/styles.scss
  setup/site/theme/styles.css
  setup/site/theme/templates/home.php
Labels: enhancement

#25 Add Prettier Action
  .github/workflows/prettier.yml
  .prettierignore
  .prettierrc.js
  setup/site/theme/index.php
  setup/site/theme/templates/home.php
Labels: enhancement

#26 Update to latest Prettier action
  .github/workflows/prettier.yml
Labels: enhancement

#27 Runs PHP Action on the next branch also
  .github/workflows/php.yml
Labels: enhancement

#28 Updates Prettier action to latest supporting plugins
  .github/workflows/prettier.yml
Labels: enhancement

#29 Corrects copy method
  README.md
Labels: enhancement

#30 Add more meta options
  core/meta.php
Labels: enhancement

#31 New features
  .github/workflows/php.yml
  .github/workflows/prettier.yml
  .gitignore
  .htaccess
  .prettierignore
  .prettierrc.js
  LICENSE
  README.md
  core/config.php
  core/constants.php
  core/content.php
  core/markdown.php
  core/meta.php
  core/posts.php
  core/theming.php
  setup/.htaccess
  setup/index.php
  setup/site/pages/404.md
  setup/site/pages/default.md
  setup/site/pages/hello-world.md
  setup/site/theme/footer.php
  setup/site/theme/header.php
  setup/site/theme/index.php
  setup/site/theme/src/styles.scss
  setup/site/theme/styles.css
  setup/site/theme/templates/home.php
Labels: enhancement, new feature
